services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: deeppick_ai_frontend
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: ["python", "main.py"]

  db:
    image: postgres:15
    container_name: deeppick_ai_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: deeppick_ai_backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
  trainer:
    build:
      context: ./trainer
      dockerfile: Dockerfile
    container_name: deeppick_ai_trainer
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./models:/models
    command: ["tail", "-f", "/dev/null"]
  predicter:
    build:
      context: ./predicter
      dockerfile: Dockerfile
    container_name: deeppick_ai_predicter
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./models:/models
    command: ["tail", "-f", "/dev/null"]
  dev:
    build:
      context: ./development
      dockerfile: Dockerfile
    container_name: deeppick_ai_dev
    env_file:
      - .env
    volumes:
      - ./svenskaspel:/app/svenskaspel

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password


volumes:
  postgres_data:
